### ISSUE TITLE
Add a cvar to remove screen shaking

### ISSUE THREAD

**Issue by mxpph** [YaLTeR/BunnymodXT#112]
(Enhancement) Could remove punchangle to improve quality of life when testing/running, in the form of a cvar such as `bxt_shake_remove`.

**Comment by YaLTeR** [comment]
What screen shake is there apart from punchangle?

**Comment by mxpph** [comment]
Edited to make more sense

**Comment by SmileyAG** [comment]
Sorry for the message after a long time, but I want to say that `bxt_shake_remove` and `bxt_remove_punchangles` added starting from the **January 16 2023** release, therefore I am closing this issue as it not actual
