### ISSUE TITLE
Draw player box in freecam

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/BunnymodXT#118]

**Comment by SmileyAG** [comment]
@YaLTeR You should close issue in favor of https://github.com/YaLTeR/BunnymodXT/pull/130

https://user-images.githubusercontent.com/58108407/129994437-f03d4274-7efd-4149-bdb6-70a99a0baeeb.mp4

**Comment by YaLTeR** [comment]
Oh yeah I guess. The issue was about drawing some box by default when you're in freecam, but I'm not sure if that's needed. Either way it's simple to implement now.
