### ISSUE TITLE
Cheat commands for setting origin and velocity

### ISSUE THREAD

**Issue by Matherunner** [YaLTeR/BunnymodXT#12]
At times it can be useful to set origin and velocity during the planning or testing phase. Setting velocity can be used for quickly checking the feasibility of routes and strategies without pulling out a gauss or doing damage boosts.

The command for setting origin should be straightforward:

```
bxt_ch_set_origin x y z
```

We could also have a command for offsetting origin:

```
bxt_ch_offset_origin dx dy dz
```

There could be three ways to set velocity:

```
bxt_ch_set_velocity_cartesian x y z
bxt_ch_set_velocity_spherical pitch yaw mag
bxt_ch_set_velocity_viewangles mag
```

The commands should be self-explanatory. The first sets the x, y, z components directly. The second takes two angles and the magnitude of velocity as part of a spherical coordinate system. The third is equivalent to the second except `pitch` and `yaw` are set to the current viewangles.

**Comment by YaLTeR** [comment]
`bxt_ch_set_velocity_cartesian` should be simply `bxt_ch_set_velocity`. Also perhaps shorten `set_velocity` and `set_origin` to `setvel` and `setpos`?

**Comment by Matherunner** [comment]
Added. The last two ways of setting velocity have been merged into `bxt_ch_set_vel_angles`. An underscore is added for consistency with `bxt_ch_set_health` and `bxt_ch_set_armor`.
