### ISSUE TITLE
Can't really use the editor

### ISSUE THREAD

**Issue by Xzjosh** [YaLTeR/BunnymodXT#120]
I hate leaving issues but I can't do anything in editor. I can't use Gold source because I can't press play and in half life steam I can't make any thing and I don't have a cursor. What should I do. Once again I don't like leaving issues but I really don't know what to do.

**Comment by YaLTeR** [comment]
You want to use Goldsrc Package 1.36 (not 2) or latest Steam Half-Life (`version` in console should say build number above 6153). Then you need to set `m_rawinput 1` in the console and it should work. For further questions you can use the #goldsrc-tas channel on our Discord: https://discord.gg/sourceruns
