### ISSUE TITLE
Latest release not injecting

### ISSUE THREAD

**Issue by crwn1337** [YaLTeR/BunnymodXT#127]
https://github.com/YaLTeR/BunnymodXT/tree/aug-1-2020 doesnt inject, no console or anything

https://github.com/YaLTeR/BunnymodXT/tree/jun-21-2020 injects and is working fine

Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 09:10:05 Jul  7 2017 (7561)

**Comment by YaLTeR** [comment]
Check that it's not your antivirus blocking it. Nothing changed in that release that could've affected it.

**Comment by crwn1337** [comment]
it isnt my antivirus, i have windows defender completely disabled and no other antivirus installed

**Comment by YaLTeR** [comment]
Does anything else happen when you try injecting it? What does the injector say? What if you start HL via the injector?

**Comment by crwn1337** [comment]
> Does anything else happen when you try injecting it?
it doesnt even inject

> What does the injector say?
Successfully opened the process.
LoadLibrary failed. This usually means that you don't have BunnymodXT.dll in the same folder as the injector.
(i have the dll in the same folder)

> What if you start HL via the injector?
it works, but then half life wont launch "Failed to initialize authentication interface. Exiting..."

**Comment by YaLTeR** [comment]
Ping
