### ISSUE TITLE
bxt_hud_useables 1 cause crashing in Counter-Strike: Condition Zero Deleted Scenes

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/BunnymodXT#141]

**Comment by SmileyAG** [comment]
That what VS Debugger shows me.
![unknown](https://user-images.githubusercontent.com/58108407/107257552-3aba0a00-6a54-11eb-9f28-63ecf3f83b00.png)

**Comment by YaLTeR** [comment]
Can't pinpoint the issue from this screenshot alone. Someone would have to look at this more in depth.

**Comment by hobokenn** [comment]
it is crashing because the offset for `ObjectCaps` is 0x18 in CZDS

**Comment by SmileyAG** [comment]
> 
> 
> it is crashing because the offset for `ObjectCaps` is 0x18 in CZDS

Can you make pull request with that changes?

**Comment by hobokenn** [comment]
> 
> 
> > it is crashing because the offset for `ObjectCaps` is 0x18 in CZDS
> 
> Can you make pull request with that changes?

i wouldn't know how to do that without breaking the current offset, the current one is also wrong for spirit based mods

**Comment by SmileyAG** [comment]
I should manually close this issue, since it got fixed in #155 (https://github.com/YaLTeR/BunnymodXT/pull/155/commits/37e8c53acb9292d4c7834e1b432da8d84d3833b5#diff-7e7d27826cbffc76caea454a313ac0c866da8271fbc1b4b508ab2af9aef9464eR560)
