### ISSUE TITLE
some way to stop or disable bunnysplit

### ISSUE THREAD

**Issue by hobokenn** [YaLTeR/BunnymodXT#144]
more often than not i find myself not wanting to deal with livesplit for a short period of time, e.g. in the middle of attempts i might want to practice, run ILs or time some strat and for that i need to quit livesplit. it would be better if i could shutdown the pipe for the time being and then reset it when i want it back. so i was thinking of just adding a similar struct as the reset one, but with just shutdown(). don't know if there is more clever way of doing that.

**Comment by YaLTeR** [comment]
I don't remember too well how BunnySplit integration is implemented exactly, so I don't have a way off the top of my head.

> struct

wdym?

**Comment by hobokenn** [comment]
> wdym?

like this one https://github.com/YaLTeR/BunnymodXT/blob/master/BunnymodXT/modules/HwDLL.cpp#L2167-L2176

**Comment by YaLTeR** [comment]
Ah, so "console command" rather. The struct is just an implementation detail of console commands.

**Comment by hobokenn** [comment]
yeah
