### ISSUE TITLE
The parameter is incorrect error

### ISSUE THREAD

**Issue by hellothere1245** [YaLTeR/BunnymodXT#145]
i keep getting an error that says: Error creating process: The parameter is incorrect.
![image](https://user-images.githubusercontent.com/67892593/110233879-52878f80-7f27-11eb-904a-7818fa076efb.png)
and this is the setup in my folder:
![image](https://user-images.githubusercontent.com/67892593/110233889-6206d880-7f27-11eb-9458-c8ab81d1ccd6.png)

**Comment by YaLTeR** [comment]
How are you running it?

**Comment by hellothere1245** [comment]
just with the injector and i runed it as adminastrator
