### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by trudruchocolatemilk** [YaLTeR/BunnymodXT#151]
when trying to inject, i get this error, even though the file is in the correct place 
![image](https://user-images.githubusercontent.com/43690740/119066523-f7096180-b9ad-11eb-9a08-f460eb1cad9d.png)

**Comment by YaLTeR** [comment]
Try this: https://github.com/YaLTeR/BunnymodXT-Injector/releases/tag/v3.1

**Comment by YaLTeR** [comment]
Check that your antivirus is disabled. They sometimes delete the dll.

**Comment by trudruchocolatemilk** [comment]
the dll is still there

**Comment by YaLTeR** [comment]
Please ask in discord.gg/sourceruns in #goldsrc-help
