### ISSUE TITLE
Game crashes when I load a map

### ISSUE THREAD

**Issue by TheOverlordBunny** [YaLTeR/BunnymodXT#167]
I'm using BunnymodXT (.DLL from Jan 11, 2021, Injector v3.1)
I am using the latest Steam update
Here's the video that shows about everything else you need to know
https://www.youtube.com/watch?v=IAjHZZsdGso

**Comment by YaLTeR** [comment]
That's weird

**Comment by hobokenn** [comment]
@TheOverlordBunny switch to OpenGL in video settings

**Comment by YaLTeR** [comment]
Probably that yeah

**Comment by TheOverlordBunny** [comment]
It still crashes after switching to OpenGL :/
