### ISSUE TITLE
Build issue with BunnymodXT

### ISSUE THREAD

**Issue by mert574** [YaLTeR/BunnymodXT#18]
Can you release linux builds too? I'm having trouble when trying to build

**Comment by Matherunner** [comment]
What was the error you saw?

Most projects don't distribute linux binaries because different linux distros come with wildly different versions of the common shared libraries, making it impossible build something that works everywhere.

**Comment by mert574** [comment]
I think the problem is between taslogger and rapidjson.

`~/BunnymodXT$ make
[  3%] Building CXX object taslogger/CMakeFiles/taslogger.dir/src/reader.cpp.o
In file included from /home/irl/BunnymodXT/taslogger/./taslogger/reader.hpp:6:0,
                 from /home/irl/BunnymodXT/taslogger/src/reader.cpp:4:
/usr/local/include/rapidjson/reader.h: In instantiation of ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseNumber(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = InternalHandler; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’:
/usr/local/include/rapidjson/reader.h:1384:46:   required from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = InternalHandler; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/usr/local/include/rapidjson/reader.h:487:35:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = InternalHandler; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/usr/local/include/rapidjson/reader.h:513:41:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream; Handler = InternalHandler; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/home/irl/BunnymodXT/taslogger/src/reader.cpp:728:63:   required from here
/usr/local/include/rapidjson/reader.h:1323:22: error: ‘class InternalHandler’ has no member named ‘RawNumber’
                 cont = handler.RawNumber(str, SizeType(length), false);
                      ^
/usr/local/include/rapidjson/reader.h:1335:22: error: ‘class InternalHandler’ has no member named ‘RawNumber’
                 cont = handler.RawNumber(str, SizeType(length), true);
                      ^
taslogger/CMakeFiles/taslogger.dir/build.make:86: recipe for target 'taslogger/CMakeFiles/taslogger.dir/src/reader.cpp.o' failed
make[2]: *** [taslogger/CMakeFiles/taslogger.dir/src/reader.cpp.o] Error 1
CMakeFiles/Makefile2:394: recipe for target 'taslogger/CMakeFiles/taslogger.dir/all' failed
make[1]: *** [taslogger/CMakeFiles/taslogger.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

Hope it will not be hard to read

**Comment by Matherunner** [comment]
A change in API in the latest version of rapidjson broke the build. Please use [rapidjson v1.0.2](https://github.com/miloyip/rapidjson/releases/tag/v1.0.2) for now until I update the code.

**Comment by mert574** [comment]
Thanks, worked ! Successfully built.

But i also had to install GL:

`sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev`
