### ISSUE TITLE
the injector won't download

### ISSUE THREAD

**Issue by PyroLikesPizza** [YaLTeR/BunnymodXT#187]
whenever I try to download the injector, opera gx and google chrome just says it's a virus, and they prevent me from downloading it

**Comment by YaLTeR** [comment]
It's false flagged by antiviruses. You'll have to make an exception for the injector.

**Comment by PyroLikesPizza** [comment]
how do I do that?

**Comment by PyroLikesPizza** [comment]
and my antiviruses are turned off as well???

**Comment by PyroLikesPizza** [comment]
nevermind, realtime security was the problem, thanks for helping though!

**Comment by YaLTeR** [comment]
That makes sense, cool
