### ISSUE TITLE
trouble inputting hold key bhop scripts for halflife 

### ISSUE THREAD

**Issue by D3C4D4NC3** [YaLTeR/BunnymodXT#19]

**Comment by Matherunner** [comment]
Could you describe in more detail what issue you are facing?

**Comment by D3C4D4NC3** [comment]
i managed to sort it with an external program

**Comment by mikesmiffy128** [comment]
Is there a reason you can't just use bxt_autojump?

**Comment by YaLTeR** [comment]
Is your issue that you can't use _special scripts in latest steam HL?
