### ISSUE TITLE
bxt_autorecord is still not fixed (FIXED)

### ISSUE THREAD

**Issue by khanghugo** [YaLTeR/BunnymodXT#21]
They Hunger Steampipe v1.1 and 1.1.0.0 (idk the liblist says it) on Half-Life latest steam version cant use your feature. I really fuck up about it
maybe the game just fucks up itself

**Comment by YaLTeR** [comment]
What doesn't work?

**Comment by YaLTeR** [comment]
No, what doesn't work in autorecord?

Latest Steam is the best for TASing.

**Comment by khanghugo** [comment]
The bxt_autorecord does rename the demo with the name "demo_1" but when I hit the changelevel trigger, it doesn't split/record anymore. I'm not on PC right now so I cant test if the load works or not

**Comment by YaLTeR** [comment]
In latest steam demos go through changelevels. You need to use playdemo to play them though.

**Comment by khanghugo** [comment]
Maybe I am just mistaken about the steampipe version but TH has a steampipe patch, before I had patched it, the bxt_autorecord didnt work, had the same issue like what I have mentioned

**Comment by khanghugo** [comment]
Okay it's my bad, the steampipe works but the older version doesn't work but nevermind

**Comment by YaLTeR** [comment]
The older version as in WON? Because yes, that's broken, and it's broken hard in the engine, and I'm not fixing that.

**Comment by khanghugo** [comment]
Okay im just stupid, i use viewdemo instead of playdemo. There is no issue here sorry Xd
