### ISSUE TITLE
Suggestion for bxt_timer_autostop

### ISSUE THREAD

**Issue by khanghugo** [YaLTeR/BunnymodXT#22]
Can you add more values which stand for others timer stop circumstance? For example, "2" means when you end a chapter, the timer will stop, we can use either map list or map's name to know what chapter we're playing. "3" means when you end a map, the timer will stop. I know bxt_autopause is a thing but this may be a bit more precise and easier to use since im a pleb

**Comment by YaLTeR** [comment]
Why close?

**Comment by khanghugo** [comment]
WHAT, are there people who read this?

**Comment by YaLTeR** [comment]
Yes, of course I read this.
