### ISSUE TITLE
Make bxt_novis not affect gameplay

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/BunnymodXT#225]
Is it possible to remove PVS for player and not let allow that for NPCs somehow?

Not want to brainwash with HLSDK & engine code for find workaround way... so, @YaLTeR, some thoughts?

```
<-- — 15.11.2021
yeah, it affects (shows) entities that would normally be outside of PVS and some of those could behave differently when outside of it 
dunno any particular cases myself, but i guess quad does))
quadkid — 15.11.2021
yeah, the ninja run patterns was different in my RP TAS when I tried 3rd person shots with novis
<-- — 16.11.2021
yea antoher PVS example is the op4 RTA trick ppl do these days
(aka if you had novis 1 for that you wouldnt be able to do it)
since the dying soldier would be loaded
```

**Comment by YaLTeR** [comment]
No, I've no clue about this.

**Comment by SmileyAG** [comment]
I did little experiments in `AddToFullPack` function of HLSDK and found that PVS for player can be removed with rid that check: 

https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/client.cpp#L1114-L1122
