### ISSUE TITLE
bxt_bhopcap crashes the game when the bhop cap funcs aren't found

### ISSUE THREAD

**Issue by chinese-soup** [YaLTeR/BunnymodXT#228]
When PM_Preventbunnyblablabla is not found bxt_bhopcap shouldn't be registered, rn it's always registered in the engine and changing the cvar crashes the game on games like HL WON.

**Comment by YaLTeR** [comment]
It's used by the TAS support to check whether the bhop cap is available. It's always registered so that even if the bhop cap func isn't found you can still manually set it to 1 and have the TAS support work correctly.

**Comment by hobokenn** [comment]
How does it crash? I thought we fixed that in https://github.com/YaLTeR/BunnymodXT/commit/c1d03041b2fa3806e3c568e994136aef2b9acf9b

**Comment by chinese-soup** [comment]
oops, ancient version of bxt accidentally in my wine goldsrcpkg install)

**Comment by hobokenn** [comment]
Not really accidental, i didn't update gsp bxt after latest release because i assumed every user of gsp is a windows user and there it is updated with an autoupdater.
