### ISSUE TITLE
bxt_bhopcap not detected in Half-Life 1.1.1.0 (WON)

### ISSUE THREAD

**Issue by Razcoina** [YaLTeR/BunnymodXT#229]
Whenever I try using this command the engine can't detect it (as if it was invalid). However, bxt_bhopcap_prediction is valid. How can that be?

**Comment by hobokenn** [comment]
I can add support for this version, it is missing just a couple of important functions, but if your intention is to speedrun, this version of half-life is not allowed. Here's the build https://github.com/hobokenn/BunnymodXT/suites/4478527929/artifacts/119239934

**Comment by Razcoina** [comment]
Thank you! Just one more question: is this compatible with linux if used with the windows injector (via wine)?

**Comment by YaLTeR** [comment]
> How can that be?

bxt_bhopcap controls a piece of code in server.dll while bxt_bhopcap_prediction controls a piece of code in client.dll, which is why it's possible that one but not the other is found.

> is this compatible with linux if used with the windows injector (via wine)?

Yes.

**Comment by Razcoina** [comment]
Alright. I guess that solves this little problem. Thanks guys!!!
