### ISSUE TITLE
If you are online, please fix this

### ISSUE THREAD

**Issue by khanghugo** [YaLTeR/BunnymodXT#23]
s03-j > s03Lj for object boost D:
vid for proof: https://youtu.be/n2eLYuDtUCY
edit: I DONT USE Ins cuz im a pleb

**Comment by khanghugo** [comment]
i think you are still online, arent you?

**Comment by YaLTeR** [comment]
Could you record and send taslog of that line with and without `l`? You do the `bxt_taslog` console command before that line, then `bxt_taslog` after that line and then upload `taslogger.log` from the Half-Life folder.

**Comment by khanghugo** [comment]
I dont know if I did I did it correctly or not. I bxt_taslog before the jump and after the long strafe 
with l: https://drive.google.com/file/d/0B5SZhJ0BXMWROWZpT2RRT3htaW8/view?usp=sharing
without l: https://drive.google.com/file/d/0B5SZhJ0BXMWRUktRYlJRMkJ1dUE/view?usp=sharing

**Comment by YaLTeR** [comment]
I can't immediately see why this bug occurrs, but don't close this issue, we'll figure it out.

**Comment by YaLTeR** [comment]
I think I found the issue.

**Comment by khanghugo** [comment]
Are you gonna release the fixed version when you finish full Half-Life TAS like you did before?

**Comment by YaLTeR** [comment]
I'm gonna release the fixed version when you add me on steam so I can send it to you for testing.

**Comment by khanghugo** [comment]
B-but you can make a "BXT Beta" repo so everyone can test it. However, I've sent you friend invitiation on steam

**Comment by YaLTeR** [comment]
Fixed in https://github.com/YaLTeR/BunnymodXT/commit/7fc06b66aa4c20d6986d058cf17da17eed076e91
