### ISSUE TITLE
Gauss fires when the RMB is pressed on Windows 10

### ISSUE THREAD

**Issue by n1kodim** [YaLTeR/BunnymodXT#235]
https://www.youtube.com/watch?v=OuUjUCkvezE

if print +attack2 in console, then it doesn't happen

**Comment by YaLTeR** [comment]
Uh, why do you think this is a BXT issue?..

**Comment by n1kodim** [comment]
Maybe it will be possible to fix this.
Why is this happening?

**Comment by YaLTeR** [comment]
I don't know? Please ask in https://discord.gg/sourceruns
