### ISSUE TITLE
TAS editor: show entity paths

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/BunnymodXT#260]
Very useful for object boosting and potentially other entity interaction. Example: yellow line here.

![image](https://user-images.githubusercontent.com/1794388/152144223-5bec7ff5-0606-4d0e-a269-4903fcec23c0.png)

**Comment by SmileyAG** [comment]
Can be closed in favor of https://github.com/YaLTeR/BunnymodXT/commit/85f1a2d76555069ecb96a3b7eb6fe70abbb9b54c?

**Comment by YaLTeR** [comment]
I suppose that covers one of the main use cases
