### ISSUE TITLE
What does "w" do in the autofuncs?

### ISSUE THREAD

**Issue by khanghugo** [YaLTeR/BunnymodXT#27]
`w` ecx dee

**Comment by YaLTeR** [comment]
Duck **W**hen Jump - ducks on the jump frames. It's for automatic LJ.

**Comment by khanghugo** [comment]
wait, you add it, do you? i thought you hadnt added it

**Comment by YaLTeR** [comment]
It's been there forever. Also please don't make issues for questions, you can always contact me elsewhere. Issues are for bug reports or feature suggestions.
