### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/BunnymodXT#279]
# Main:

- **Toggling with** `bxt_rpc` **command** [Looks impossible to implement, since game crashes with un-loading RPC)
- **Map name** [Done]
- **Game directory** (thanks @ScriptedSnark for suggest) [Done]
- **Thumbnails** [Done]
- **BXT Timer** [Done]
- **Server time** [Not needed?]
- **Max FPS, Difficulty, Bhopcap (On/Off), Autojump (On/Off)** [FPS / Skill only]
- **Simple chapter system: hardcoding map names for chapters of common games** [Done]

# Extra:

- **Advanced chapter system: allow to customize for list of map names of chapters in some file, like** `rpc_chapters.txt`

**Comment by ScriptedSnark** [comment]
Also, I think it worth to add to **Main** goals a output of current `gamedir` (for example, `valve_WON`)

**Comment by YaLTeR** [comment]
Someone would need to make screenshots too, like in OpenAG
