### ISSUE TITLE
I dont know if this is a bug or not

### ISSUE THREAD

**Issue by khanghugo** [YaLTeR/BunnymodXT#28]
Wait, is this a bug? 
Vid: https://youtu.be/_Xb_UG6AWsM

**Comment by khanghugo** [comment]
Oh i forgot to tell you that i reproduce the bug with different speed so the result may not come to the same, i can redo it tomorrow

**Comment by khanghugo** [comment]
Oh wait this isnt a bug, sorry

**Comment by khanghugo** [comment]
Oh wait, i think it's a bug, isnt it?

**Comment by khanghugo** [comment]
Im writing the context, sorry for the latest wall of text i wrote, im reporting this bug again

**Comment by khanghugo** [comment]
In the vid, forget about the 1 and 3 because i was wrong about them, look at the 2, why doesnt it ducktap "as soon as it hits the ground?

**Comment by YaLTeR** [comment]
Please use descriptive issue names and describe the issue in detail.

**Comment by khanghugo** [comment]
Sorry yalter, please refresh your page

**Comment by khanghugo** [comment]
Why does the first circumstance can perform a duck tap at the very edge of the block but the rest doesnt? What am i doing wrong here, i dont really know if it is a bug or not. More, in the 2, it doesnt perform any ducktap even though there isnt 'l'

**Comment by khanghugo** [comment]
okay im gonna rewrite this in detail, closed

**Comment by khanghugo** [comment]
okay it's my bad, it isnt a bug, it's just my mistake
