### ISSUE TITLE
[CS] [8684] Update patterns

### ISSUE THREAD

**Issue by rollangles** [YaLTeR/BunnymodXT#280]
# Counter-Strike

Became interested in TAS - downloaded and injected the binary and saw some warnings due to outdated patterns. I decided to open disassembler and find the right bytes for the latest CS update (Steam) - not including HL stuff.
## Client
**CStudioModelRenderer::StudioSetupBones**
> 83 EC 44 53 55 8B E9 56 57 33 FF 8B 45 30

## Server
**PM_FlyMove**
> 81 EC ?? ?? ?? ?? 53 8B 1D

**PM_WalkMove**
> 8B 0D ?? ?? ?? ?? 81 EC ?? ?? ?? ?? D9 81 ?? ?? ?? ?? D8 1D ?? ?? ?? ?? DF E0 25 ?? ?? ?? ?? 75

**PM_PlayerMove**
> 83 EC 10 A1 ?? ?? ?? ?? 8B 4C 24 14

**CBasePlayer::TakeDamage**
> 83 EC 34 53 8B 5C 24 48

**CBasePlayer::ForceClientDllUpdate**
> 56 8B F1 83 C8 FF 89 86

**CBasePlayer::CheatImpulseCommands**
> 81 EC ?? ?? ?? ?? 53 56 57 68

**CBaseMonster::Killed** *
> 56 8B F1 8B 86 ?? ?? ?? ?? 84 C0
 
**DispatchRestore** *
> 81 EC ?? ?? ?? ?? 53 8B 9C 24 ?? ?? ?? ?? 55 33 ED

**Comment by YaLTeR** [comment]
Thanks! Mind submitting a pull request with these patterns?

**Comment by SmileyAG** [comment]
@playermove 

StudioSetupBones needs for `bxt_viewmodel_` commands
PM_ needs for TAS debug
TakeDamage for TAS debug + fixing hornet crash in hl1 speedruns
ForceClientDllUpdate for fix resetting ammo counter in hl1 games + offsets for `bxt_hud_useables`
CheatImpulseCommands needs for `_bxt_norefresh 1`
CBaseMonster::Killed - for tracking if npc been killed or not for `bxt_timer_autostop` in some hl1 mods
DispatchRestore - for tracking globalstate on last map in HL: Blue Shift speedruns

So, `DispatchRestore` and `CBaseMonster::Killed` can be ez removed from patterns list
