### ISSUE TITLE
"bxt_hud_color" doesn't appear to work in config files.

### ISSUE THREAD

**Issue by NeoSquared** [YaLTeR/BunnymodXT#29]
So in my userconfig.cfg I have this line: 
>bxt_hud_color "0 206 209"

And when I launch my game and inject BmodXT, the HUD is the default yellow-ish color, and typing bxt_hud_color in the console returns two empty quotation marks, as if the command didn't have a value. However, when in game, the command works fine and I can change the HUD colors properly.

**Comment by YaLTeR** [comment]
Use the second method of launching BXT, not the start and then inject one.
