### ISSUE TITLE
bxt_hud_inwater

### ISSUE THREAD

**Issue by nxrner** [YaLTeR/BunnymodXT#298]
In special cases visual in-water effects don't really indicate if you can clip through walls with the new skip (for example, skybox water), so it would be nice to have a hud which accurately indicates if you can clip in this exact moment.

**Comment by SmileyAG** [comment]
I'm already implemented `bxt_hud_waterlevel` command in https://github.com/YaLTeR/BunnymodXT/pull/291 request, wait for new BXT release.
