### ISSUE TITLE
BXT Console Commands missing

### ISSUE THREAD

**Issue by AlexHurd** [YaLTeR/BunnymodXT#30]
Not all of the console commands listed in the wiki are present in game, such as bxt_taslog.
https://i.imgur.com/5ODo3Dc.png
I've tried several different ways of opening both hl.exe and injector.exe together, and in some ways, there are even more commands missing, and I could not find a way to have all of them.
Here are the screencaps for the log as well:
http://i.imgur.com/Vqtzn9y.png
http://i.imgur.com/YCVtbSo.png
http://i.imgur.com/xc4aJPK.png
http://i.imgur.com/yZbl7Mx.png

I used a .bat file to open the injector and hl.exe.

**Comment by YaLTeR** [comment]
That's normal, all commands are supported maybe only by the latest Steam Half-Life, older ones have some commands missing. That `Error hooking sw.dll` line, on the other hand, needs a fix from my part (not that it would enable more commands in this case, just an unrelated issue).

**Comment by AlexHurd** [comment]
So I tried opening Half-Life on Steam and using the injector, and all the commands still didn't appear, plus the game automatically closes whenever I try to load a map. Same thing happens when I load a map and then start the injector, it just closes.

**Comment by YaLTeR** [comment]
That's strange.

**Comment by KaaCI05** [comment]
i have the same promblem... :(

**Comment by MysticalLightObject** [comment]
I've found the solution: once you launch the hl.exe in safe mode (software rendering) the exact same symptoms show up.

@AlexHurd @KaaCI05 
Steps to resolve:
1) Launch the .bat file (or hl.exe with -steam parameter)
2) Open the console and type in `exec default.cfg` (this step may not be necessary)
3) Set the OpenGL renderer in Video settings
4) Exit the game and launch the .bat file. The timer_* commands should now be present

**Comment by VEZDAZ** [comment]
![image](https://user-images.githubusercontent.com/60209517/72958787-50ad4c00-3db9-11ea-805b-d4b672b3b3b7.png)
I tried to fix redist, this not working. Pls help.

**Comment by VEZDAZ** [comment]
Goldscr package 2.3, i do litliterally nothing, and this happend. I tried to install another version, (1.32), I tried in .bat change directory, and anyway nothing happend with DLL...

**Comment by YaLTeR** [comment]
Could you all try again with the latest BXT version? I'm gonna close this issue otherwise because it's not clear to me what build is affected and what's going on.

**Comment by derric-young** [comment]
why is bxt_autojump not found when playing big lolly

**Comment by derric-young** [comment]
im banned from that sever

**Comment by derric-young** [comment]
goldsrc pagage auto updates bxt

**Comment by Ayman12346** [comment]
![Uploading 2022-02-07_164747.png…]()

**Comment by Ayman12346** [comment]
![Uploading 2022-02-07_164747.png…]()

**Comment by derric-young** [comment]
Hello. This is me from the future. I've long since abandoned half life speedrunning as a whole. Idk what the image sent means. Honestly. half life speedrunning is what got me into speedrunning as a whole. I'm currently in into BEJEWELED speedrunning?!??!!?? So. If your wondering if I'm fine or not. I'm fine. Should i do a final send off or not. 2 years since the start of me speedrunning around when i first got my computer that I still use to this day. That's all I gotta say here. That's all.

**Comment by derric-young** [comment]
And yes this is the most random thing to say
