### ISSUE TITLE
[Linux] Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by parklez** [YaLTeR/BunnymodXT#33]
OS: Elementary OS Loki 0.4.1 x64
I used the helper script, game doesn't launch and the output is "Illegal instruction (core dumped)".

**Comment by YaLTeR** [comment]
From Discord: the CPU in question is i5 650.

**Comment by YaLTeR** [comment]
The issue was that I was compiling with `-march=native` as opposed to `pentium-m` as in CMakeLists.txt.
