### ISSUE TITLE
When Injected BunnymodXT game crashes

### ISSUE THREAD

**Issue by usras1** [YaLTeR/BunnymodXT#35]
Hello! when i inject bunnymodxt in half life and i press new game or load game it crashes ..? what do i do?

**Comment by YaLTeR** [comment]
Tell me exactly which Half-Life you're using, make sure you have the latest BunnymodXT.dll (download it in the Releases section here) and post screenshots of the BXT debug console.

**Comment by usras1** [comment]
i us ehalflife 1.1.0.8 Game of the year edition and when my game crashes the console crashes as well i forgot to mention,i have the latest bunnymodXT.dll  ill send a screenshot

**Comment by YaLTeR** [comment]
It might be that this particular HL version crashes in BXT. You should try a different HL version. Unfortunately there's not much I can do without having that specific version myself.
