### ISSUE TITLE
question: can you play Bunnymod XT and have amxx plugins enabled?

### ISSUE THREAD

**Issue by Lopol2010** [YaLTeR/BunnymodXT#358]
I want to make TAS using certain auto-bhop plugin (at least). Thanks in advance.

**Comment by YaLTeR** [comment]
You could try installing amxx and running BXT on a local server, but this is not a supported use-case, so it may not work.

> auto-bhop

Why do you need that with BXT? It already has autobhop.

**Comment by Lopol2010** [comment]
I tried local server and indeed it didn't worked for me. (ReHLDS server and cs 1.6 with injected BXT, cs is crashing when enabling TAS editor or loading script, I don't remember exact scenario)

>Why do you need that with BXT? It already has autobhop.
Plugin has these differences:
1. You can switch between jumping and DD almost seamlessly in terms of speed, basically no friction when you land after jump. When I tried this with BXT, friction makes me loss 30% speed (when scripted to DD right after land after jump)
2. Plugin makes you jump higher (it sets vertical velocity on ground touch), this could be simulated with sv_gravity with BXT I guess.

**Comment by YaLTeR** [comment]
> I tried local server and indeed it didn't worked for me. (ReHLDS server

By local server I mean the one you get with create server in-game. Dedicated server will definitely not work.

**Comment by Lopol2010** [comment]
This type of server didn't worked too, when I load script my fps becomes always 1-4 and it lagging hard, the segmets also become broken for some reason, the only way I can do TASing is through "map" command with almost all plugins not work there.

**Comment by YaLTeR** [comment]
Yeah, unfortunately I don't think it's possible to get this to work easily. BXT is developed for singleplayer only, so the code makes a lot of assumptions that do not hold for multiplayer. I don't think it would be easy to fix it either.

**Comment by khanghugo** [comment]
> You can switch between jumping and DD almost seamlessly in terms of speed, basically no friction when you land after jump. When I tried this with BXT, friction makes me loss 30% speed (when scripted to DD right after land after jump)

This seems like 1000fps ducktap, which makes it not losing 4% of speed each ducktap in 100fps. You can make a 1000fps run if you want to do that.

> Plugin makes you jump higher (it sets vertical velocity on ground touch), this could be simulated with sv_gravity with BXT I guess.

CS1.6 jump height is affected by stamina as well. There is a CS1.6 specific bxt_ cvar called `bxt_remove_stamina` that you can use to remove stamina, which makes it jumps exactly like HL is. You can get the version with that by downloading BXT from Actions page.

**Comment by YaLTeR** [comment]
> This seems like 1000fps ducktap, which makes it not losing 4% of speed each ducktap in 100fps. You can make a 1000fps run if you want to do that.

At 1000 FPS you will still have one frame of friction. You can avoid friction altogether by using 0 ms ducktaps which use 10000000 FPS or similarly large.
