### ISSUE TITLE
HUD to track Nihilanth's AI for full game TASes or new players

### ISSUE THREAD

**Issue by Matherunner** [YaLTeR/BunnymodXT#38]
The cvar may be called `bxt_hud_nihilanth`.

It may be helpful for a full game TAS or new player to track Nihilanth's AI to get a sense of progress on making his head open, which boils down to measuring a few state information, like _level_ and _irritation_.

In addition, a time-saving trick that is rarely done in today's runs on the leaderboard, but was done in HL21, is to saveload after at least 10 health spheres have been absorbed. This will nullify the rest of the health spheres. This requires tracking the number of active health spheres.

See https://www.jwchong.com/hl/monsters.html for details on Nihilanth's AI.

![nihilanth-hud](https://user-images.githubusercontent.com/2558060/38940379-924d09ce-435c-11e8-9061-0eebde94335a.jpg)

Purpose of these values:

- **health**: affects the animation speed of Nihilanth (and therefore how quick _level_ increments), minimising the health is a priority in an optimised run
- **level**: if 10, the head should open immediately
- **irritation**: if 0, Nihilanth does not attack; if 1, _level_ may increment; if 2, the head is open; if 3, he is dead
- **recharger**: determines whether Nihilanth has found a recharger, allowing him to use it
- **spheres**: tells the runner when to saveload to nullify the rest of the spheres, which is when the count is less than or equal to 10

**Comment by execut4ble** [comment]
Damn this is cool.
