### ISSUE TITLE
BXT does not inject into half-life on Gldscr package.

### ISSUE THREAD

**Issue by AxerTheAxe** [YaLTeR/BunnymodXT#385]
Hello, sorry to bug you on here but I have asked plenty of other people for help on this and have gotten no answers. BXT does not properly inject when I launch the game with Gldscr package 2.4. I have also tried the 2005 WON package and that does not work either. I am able to get it to work by launching the steam version then launching the injector.exe but trying to use BXT with any of the launch able versions on Gldscr package. I have also tried using my own bat files to no avail. 

Sorry for any bad grammar my English is not the best.

Here are my BXT log files when I launch Half-LIfe (WON) with Gldscr package 2.4

`
Bunnymod XT version Sep  1 2022 03:05:26.
BXT: Opened the TASView pipe.
BXT: Opened the BunnySplit pipe.
SPTLib version 1.2.
SPTLib: Modules contain 4 entries.
SPTLib: Hooked 5 WinAPI functions.
SPTLib: Hooking hl.exe (start: 01400000; size: 2117000)...
BXT: [hw dll] Could not find ClientDLL_CheckStudioInterface.
BXT: [hw dll] Could not find ClientDLL_Init.
BXT: [hw dll] Could not find LoadThisDll.
BXT: [hw dll] Could not find Host_FilterTime FPS Cap Byte.
BXT: [hw dll] Could not find Cbuf_Execute.
BXT: [hw dll] Could not find Cvar_RegisterVariable.
BXT: [hw dll] Could not find R_SetFrustum.
BXT: [hw dll] Could not find Host_AutoSave_f.
BXT: [hw dll] Could not find SeedRandomNumberGenerator.
BXT: [hw dll] Could not find SCR_DrawFPS.
BXT: [hw dll] Could not find CL_Move.
BXT: [hw dll] Could not find the g_svmove pattern.
BXT: [hw dll] Could not find the sv_areanodes pattern.
BXT: [hw dll] Could not find Host_Changelevel2_f.
BXT: [hw dll] Could not find CL_Stop_f.
BXT: [hw dll] Could not find Cmd_Exec_f.
BXT: [hw dll] Could not find Cmd_ExecuteString or Cmd_ExecuteStringWithPrivilegeCheck.
BXT: [hw dll] Could not find SV_SetMoveVars.
BXT: [hw dll] Could not find R_StudioCalcAttachments.
BXT: [hw dll] Special effects of weapons will be misplaced when bxt_viewmodel_fov is used.
BXT: [hw dll] Could not find R_StudioSetupBones.
BXT: [hw dll] Disabling weapon viewmodel idle or equip sequences is not available.
BXT: [hw dll] Could not find Cvar_DirectSet.
BXT: [hw dll] Could not find Cvar_FindVar.
BXT: [hw dll] Could not find Cmd_FindCmd.
BXT: [hw dll] Could not find Cbuf_InsertText.
BXT: [hw dll] Could not find Cbuf_AddText.
BXT: [hw dll] Could not find Cmd_AddMallocCommand.
BXT: [hw dll] Could not find RandomLong.
BXT: [hw dll] Could not find SCR_BeginLoadingPlaque.
BXT: [hw dll] Could not find PM_PlayerTrace.
BXT: [hw dll] Could not find Host_Loadgame_f.
BXT: [hw dll] Could not find Host_Reload_f.
BXT: [hw dll] Could not find CL_RecordHUDCommand.
BXT: [hw dll] Could not find CL_Record_f.
BXT: [hw dll] Could not find build_number.
BXT: [hw dll] Could not find Key_Event.
BXT: [hw dll] Could not find Host_Tell_f.
BXT: [hw dll] Could not find Host_FilterTime.
BXT: [hw dll] Could not find V_FadeAlpha.
BXT: [hw dll] Could not find R_DrawSkyBox.
BXT: [hw dll] Could not find SV_Frame.
BXT: [hw dll] Could not find VGuiWrap2_ConDPrintf.
BXT: [hw dll] Could not find VGuiWrap2_ConPrintf.
BXT: [hw dll] Could not find SCR_UpdateScreen.
BXT: [hw dll] Could not find R_DrawSequentialPoly.
BXT: [hw dll] Could not find R_Clear.
BXT: [hw dll] Could not find R_DrawViewModel.
BXT: [hw dll] Could not find Mod_LeafPVS.
BXT: [hw dll] Could not find PF_GetPhysicsKeyValue.
BXT: [hw dll] Could not find SV_AddLinksToPM_.
BXT: [hw dll] Could not find SV_WriteEntitiesToClient.
BXT: [hw dll] Could not find VGuiWrap_Paint.
BXT: [hw dll] Could not find DispatchDirectUserMsg.
BXT: [hw dll] Could not find studioapi_GetCurrentEntity.
BXT: [hw dll] Could not find EmitWaterPolys.
BXT: [hw dll] Could not find S_StartDynamicSound.
BXT: [hw dll] Could not find VGuiWrap2_NotifyOfServerConnect.
BXT: [hw dll] Could not find CBaseUI__HideGameUI.
BXT: [hw dll] Could not find R_DrawWorld.
BXT: [hw dll] Could not find R_DrawEntitiesOnList.
BXT: [hw dll] Could not find R_DrawParticles.
BXT: [hw dll] Could not find BUsesSDLInput.
BXT: [hw dll] Could not find R_StudioRenderModel.
BXT: [hw dll] Could not find SPR_Set.
BXT: [hw dll] Could not find DrawCrosshair.
BXT: [hw dll] Could not find Draw_FillRGBA.
BXT: [hw dll] Could not find PF_traceline_DLL.
BXT: [hw dll] Could not find CL_CheckGameDirectory.
BXT: [hw dll] Could not find LoadAndDecryptHwDLL.
SPTLib: No hl.exe functions to hook.
BXT: Signaled the injector to resume the process.
SPTLib: No hl.exe functions to unhook.
`

![image](https://user-images.githubusercontent.com/99703210/210111178-c94b6c7a-c097-4946-b59b-1b18a5208cfb.png)

![image](https://user-images.githubusercontent.com/99703210/210111196-a16c8a24-fbf3-4a1e-aec6-b8e5534043c6.png)

**Comment by YaLTeR** [comment]
Hey, unfortunately I'm not sure I can provide any further help on top of people answering in https://discord.gg/sourceruns :/

**Comment by AxerTheAxe** [comment]
> Hey, unfortunately I'm not sure I can provide any further help on top of people answering in https://discord.gg/sourceruns :/

Got it. Thanks for taking the time to look at it anyways.

**Comment by AxerTheAxe** [comment]
If anyone else if having this issue I made a bat file that solves the issue. (For 2005 package)

`@echo off
cd "%~dp0Half-Life"
start hl.exe -steam -gl -32bpp -game valve_WON -noforcemparms
"..\RInput\RInput.exe" hl.exe
cd "%~dp0Bunnymod XT"
TIMEOUT /T 5
start Injector.exe`

**Comment by AxerTheAxe** [comment]
To close as completed
