### ISSUE TITLE
unknown format or damaged 

### ISSUE THREAD

**Issue by Yuismf** [YaLTeR/BunnymodXT#391]
I installed the new version of the .dll but im getting an error the error is ``C:\Users\ps\Downloads\1-BunnymodXT-Windows(1).7z The archive is either unknown format or damaged`` I am using windows 7 I th'nk this error caused because I am using windows 7 and i was trying to use it in ``Half Life Opposing Force`` can you help me whit that?

**Comment by YaLTeR** [comment]
Are you using 7-Zip? Try to redownload the archive, try to disable antivirus.

**Comment by Yuismf** [comment]
> Are you using 7-Zip? Try to redownload the archive, try to disable antivirus.

No I am using WinRaR and I dont know how to open as 7zip

**Comment by YaLTeR** [comment]
https://7-zip.org/

**Comment by Yuismf** [comment]
> https://7-zip.org/

Thanks if something happens ill reply to you sorry for the wait btw

**Comment by Yuismf** [comment]
> https://7-zip.org/

Thank you! it worked, if you want me to close this report say it and again thank you
