### ISSUE TITLE
GL Crosshairs

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/BunnymodXT#4]
Add a crosshair that is rendered by the game itself, instead of using sprite files.

Not only this would make the crosshairs look sharp and clean, but commands for full crosshair customization could also be added.

Would be best if it worked like this: http://tools.dathost.net/, so you could generate crosshairs using this, or even use your crosshair settings from CSGO and it'd look the same.

**Comment by Matherunner** [comment]
Doable with TriAPI. I've always wanted to have a crosshair that is crisp and doesn't depend on the weapon. TriAPI's primary advantage over `FillRGBA` is that the alpha is adjustable in the `kRenderTransAlpha` render mode.

**Comment by Matherunner** [comment]
Partial implementation in d5aff57de2291bf8a5cf0edf89173829187df5f0 in the crosshair branch. The important cvars are implemented. Although the geometries don't work exactly like CS:GO, they're not too far off. Non-classic crosshairs and outlines are not implemented.

**Comment by YaLTeR** [comment]
See https://github.com/YaLTeR/OpenAG/blob/master/cl_dll/hud_crosshairs.cpp for a nice implementation.
