### ISSUE TITLE
bxt_bhopcap does not work on Counter-Strike

### ISSUE THREAD

**Issue by derric-young** [YaLTeR/BunnymodXT#407]
for some resean. bxt_bhopcap does not work on SPEFIFICLY Counter-Strike and the Condition Zero games. All Others work fine

**Comment by derric-young** [comment]
setting it to 0 will sitll have it enabled for those games

**Comment by YaLTeR** [comment]
Are you using the latest Bunnymod XT version (Jan 16 2023)?

**Comment by derric-young** [comment]
updated it and it worked. did not even see that since it was my own instinct. who knew
