### ISSUE TITLE
Is their a way to use this mod with https://github.com/hzqst/MetaHookSv?

### ISSUE THREAD

**Issue by gitdrug** [YaLTeR/BunnymodXT#445]
Is their a way to use this mod with https://github.com/hzqst/MetaHookSv?

**Comment by YaLTeR** [comment]
If it doesn't work as is then no easy way I'm afraid.

**Comment by gitdrug** [comment]
> If it doesn't work as is then no easy way I'm afraid.

should I just find different way to uncap speed then?

**Comment by YaLTeR** [comment]
Yeah
