### ISSUE TITLE
Doesn't seem work with Xash3D

### ISSUE THREAD

**Issue by Roachdaripper** [YaLTeR/BunnymodXT#45]
It injects okay, but then causes the game to hang when a game's started.

**Comment by YaLTeR** [comment]
No wonder. BXT is _extremely_ tied to the GoldSource engine, as in the actual binary files. It might be possible to make it work with Xash3D but it would take lots of effort.

**Comment by YaLTeR** [comment]
It's probably more accurate to say that BXT is tied to the way the code is structured in the GoldSource engine, so adding support for another version of the GoldSource engine (be it an older version, or a version on the different OS) is easy, but adding support for alternative implementations (or some really old GoldSource versions which have significant code structure differences) is very hard.

**Comment by Roachdaripper** [comment]
I assumed that it'd work because on the sourceruns wiki it's mentioned that you figured out how source code works using Xash3D

**Comment by YaLTeR** [comment]
Xash3D helps to understand how GoldSource works, but it's not very related to code structure. You can program the same behavior in vastly different ways, and while you can use the programs in all of these ways to understand the behavior, they will all have different code structure.

**Comment by Roachdaripper** [comment]
Ah okay, would it be possible in future to make a Xash version of bunnymod?

**Comment by YaLTeR** [comment]
It'd be easier to just add the required things straight into Xash3D ¯\_(ツ)_/¯

**Comment by Roachdaripper** [comment]
Possible though?

**Comment by YaLTeR** [comment]
Yes but would take lots of time.

**Comment by Roachdaripper** [comment]
Darn. Thanks anyway.
