### ISSUE TITLE
bxt_fix_widescreen_fov: breaks during the changelevel

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/BunnymodXT#451]
Some explanation and fixed code:

![0](https://github.com/YaLTeR/BunnymodXT/assets/58108407/447ef27c-fecb-44d4-ab12-01276198d4fb)

Would close that issue with the coming soon PR

Next time I should be more conscious about testing features since I didn't even knew there was a such case due to the fact I didn't go through maps with `bxt_fix_widescreen_fov` enabled

**Comment by khanghugo** [comment]
Would you be interested in porting this into bxt-rs? I think it would fit bxt-rs better because it doesn't involve much stuffs and it's nice to have for video recording.

**Comment by SmileyAG** [comment]
> Would you be interested in porting this into bxt-rs? I think it would fit bxt-rs better because it doesn't involve much stuffs and it's nice to have for video recording.

I don't think that I have a feel for porting cmds up to bxt-rs due of next reason:

- Even that both tools firstly checking and getting cvar pointer if it's already registered, it's still doesn't save us somehow from the next bug, that pair injecting makes to ignore the functionality from one of them

Let's say that `bxt_force_fov` on BXT side would be used not only for the overriding FOV, but also to return value of cvar in case if enabled for other unrelated functionally (e.g. viewmodel FOV hacks)
With bxt-rs injected, all of that stuff seems to be ruined, because the cvar checks not passed, so I use it in pair only when I need it for capturing demos, otherwise I prefer to port non-related capturing cmds up from bxt-rs to BXT

From changes that I ready to do for bxt-rs is only the supporting more engine builds with offsets/patterns for video recording, so personally I don't see the feel for porting cmds to it, and I'm not interested in TAS support stuff too

But I'm wouldn't against if you would do it as long as you see it useful
