### ISSUE TITLE
Correcting +bxt_ch_hook request

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/BunnymodXT#456]
That a good addition, but I haven't looked to the request itself before, so let's see:

https://github.com/YaLTeR/BunnymodXT/blob/71f1c9a75d6e92cb1f5e48c8d380541451165ea8/BunnymodXT/modules/HwDLL.cpp#L3166

What is that random stuff does here? Please, don't add some wacky kind of that hardcoded stuff that ain't supposed to be in it, let player to set HP on their own with `bxt_ch_set_health` or using the `god` command

https://github.com/YaLTeR/BunnymodXT/blob/71f1c9a75d6e92cb1f5e48c8d380541451165ea8/BunnymodXT/modules/HwDLL.cpp#L3168

Don't make the speed is hardcoded, better to create the specified cvar for that initially, or otherwise soon or later you still would to hear from others for making that addition

Other than that, additionally, might to consider of adding draw of trace line with power of pTriAPI
Or rather re-using beam sprites from HL1 (e.g. from Gauss gun) and pEfxAPI/pEventAPI/pTriAPI/SPR_ functions to draw it

**Comment by khanghugo** [comment]
The health thing is so player won't die when going down. These parameters are hard coded so there is no need to do a lot of things just to get it to work. I agree that having another cvar to control it is nice but I just don't feel like adding some more cvars.

As for the line drawing, I did not know how to use the thing so I just skip it.

**Comment by SmileyAG** [comment]
> The health thing is so player won't die when going down. These parameters are hard coded so there is no need to do a lot of things just to get it to work.

Do you want to know what main issue with the current code? 
Well, then if there some keys with bound `+` cmds on them (e.g. `bind / +bxt_ch_hook`), then each time you spawning/going to menu/loading save = those `-` cmds will be executed (e.g. `-bxt_ch_hook`)

Now guess what would happen when you launching game and start map with bind for `+bxt_ch_hook`?
Right, you spawning as dead, since the `ch_hook_hp_before` is 0 by default

Instead of applying some value at init, I rather suggest to remove all of that, since that health thing is really not supposed to be here, I'm still on a side that player should to decide himself if he want to set HP or not

And if someone think that adding a new variable for controlling speed isn't sound as something that would clutter or be unpopular, just remember that `_offset` and `_anchor` commands is exist, so it wouldn't be worse anyway

Don't think that I'm kind of angry or smth, i'm really pleasant for everyone who putting effort in it, but I really don't like when there is hardcoding that doesn't have a real purpose for it and half ppls would easily to prefer to edit to their own preferences, so you need to think about everyone

**Comment by YaLTeR** [comment]
FWIW I was also on the edge about hardcoded HP but figured it's a specific enough functionality that it doesn't really matter. The -command issue should be fixed though.

As for speed, I see even less of a reason for it to be customizable tbh.

**Comment by khanghugo** [comment]
Thanks for pointing out the issues. I will try and fix it and see.

**Comment by SmileyAG** [comment]
> As for speed, I see even less of a reason for it to be customizable tbh.

Well, if you want to know my opinion, I prefer to have hook speed to get more lower than the current one (like 850 units)

But at the same time I don't want to force for change value due of my preferences, instead I rather prefer to have a separate cvar for that
Like that's fine what value you want to have by default, just please let others to change to their own preferences

For a long time the BXT custom triggers was hardcoded to orange color and more than half opacity
And when you see that color for a hundred times (that might not even fit to HUD color), and specifically, when map textures / lightning is too bright and have contain most of that orange color, it makes literally eyes are bleeding while trying to looking through that trigger
So I had to make a separate cvar for it to being satisfying with it

The only valid reason for hardcoding speed can be accepted in case if the code has some limitations that makes it only stable works with specific value / range of values, but that's a not case as you can see

Each time you think that some of cvar that changing only cosmetic stuff will be used only by few peoples, that completely not true
There some of stuff that I added before that ppls to use it this day, but most of them never talked about adding that (some of them afraid to bother others about that misc stuff, others are just kinda fine with what they got, but still would be cool for them to have a option for changing it in future)
