### ISSUE TITLE
LoadLibrary failed

### ISSUE THREAD

**Issue by Faervn** [YaLTeR/BunnymodXT#467]
i have tried all versions of XT and its injector. setting security permissions. disabling all forms of firewall/antivirus. running as admin. unchecking read only. ridiculous

**Comment by YaLTeR** [comment]
Please ask in https://discord.gg/sourceruns in the `#goldsrc-help` channel and say your Windows version and which Half-Life you're trying to inject into (Steam or Goldsrc Package).

**Comment by Nughu** [comment]
> Please ask in https://discord.gg/sourceruns in the `#goldsrc-help` channel and say your Windows version and which Half-Life you're trying to inject into (Steam or Goldsrc Package).
GitHub is the proper platform for stuff like this. Why even upload it here if you don't help people here?

**Comment by YaLTeR** [comment]
GitHub Issues are for actionable bugs. For debugging, especially for debugging problems unrelated to the code in this repository, it is not the right platform, no.
