### ISSUE TITLE
HL Crashes after joining a multiplayer server

### ISSUE THREAD

**Issue by Glebux** [YaLTeR/BunnymodXT#475]
title says it all
didn't test it on windows
crash dump included
![crash dmp](https://github.com/YaLTeR/BunnymodXT/assets/58988874/f551c770-9748-4d45-9f86-97ad79244ea0)

**Comment by khanghugo** [comment]
Your image is not showing. Nonetheless, as the instruction here states, DO NOT CONNECT TO SERVERS WITH BUNNYMODXT INJECTED

**Comment by Glebux** [comment]
> Your image is not showing. Nonetheless, as the instruction here states, DO NOT CONNECT TO SERVERS WITH BUNNYMODXT INJECTED
I was on my dedicated server, vac disabled

**Comment by khanghugo** [comment]
Then it is very possible you are metamod or whatever sitting between the game and the dlls. Your crash log screenshot is not showing.

**Comment by Glebux** [comment]
> Then it is very possible you are using metamod or whatever sitting between the game and the dlls. Your crash log screenshot is not showing.

Rename it to crash.dmp, i just added .png to upload it to github

**Comment by khanghugo** [comment]
Are you using metamod or anything? If not, then maybe you are running on latest Half-Life (25 anniversary). You need to roll back

**Comment by Glebux** [comment]
I'm using steam_legacy beta, and the server uses vanilla server.dll

**Comment by khanghugo** [comment]
Can you post the terminal output? Your crash log is not very helpful.

**Comment by Glebux** [comment]
```
Bunnymod XT version Dec 10 2023 22:26:41.
[DevMsg] BXT: Opened the message queue.
[DevMsg] SPTLib version 1.2.
[DevMsg] SPTLib: Modules contain 4 entries.
crash_20231211223256_3.dmp[3434171]: Uploading dump (out-of-process)
/tmp/dumps/crash_20231211223256_3.dmp
[DevMsg] BXT: Closed the message queue.
crash_20231211223256_3.dmp[3434171]: Finished uploading minidump (out-of-process): success = yes
crash_20231211223256_3.dmp[3434171]: response: Discarded=1
crash_20231211223256_3.dmp[3434171]: file ''/tmp/dumps/crash_20231211223256_3.dmp'', upload yes: ''Discarded=1''
[DevMsg] BXT: Closed the message queue.
```

**Comment by Glebux** [comment]
Also i've noticed that the crash gets triggered when shooting the glock

**Comment by khanghugo** [comment]
Is this everything in the terminal? Are you sure you are following the instructions on how to inject bxt? When you join a listen server it should print a lot in the terminal. Anyway, why is your version Dec 10? You should try using the binary from release unless you know what you are getting into.

**Comment by khanghugo** [comment]
As for how to inject BunnymodXT, I recommend checking out bxt-rs repository where there is runhl.sh file that you can use.

**Comment by YaLTeR** [comment]
BXT only supports single player. In multiplayer you're expected to get crashes and other issues because none of the code expects multiplayer.
