### ISSUE TITLE
Camera re-sets settings on lvlchange and savefile loads

### ISSUE THREAD

**Issue by M4lfr1d** [YaLTeR/BunnymodXT#482]
### This is not a major problem, but it's annoying and a bit nauseating. I guess camera options have to be set again at every load instead of the default values, so FOV (including the bxt_fix_widescreen_fov), cam values like distances and everything else is jumping from default values which causes hard camera twitching like this for 1st person view:
![1stperson](https://github.com/YaLTeR/BunnymodXT/assets/61455480/c17e7357-9dda-440e-9fd6-6d9c704816de)
mp4:
https://github.com/YaLTeR/BunnymodXT/assets/61455480/958dfb7a-a423-4db2-8576-77eb00085846

And like this for the 3rd person view:
![3rdperson](https://github.com/YaLTeR/BunnymodXT/assets/61455480/17a2a3e2-68c1-4a42-a474-c51e8b4c1518)
mp4:
https://github.com/YaLTeR/BunnymodXT/assets/61455480/b49fd50c-79e1-41c1-9c3d-7fb69ee280b8

Is there any possible way to fix this? Sorry if I missed an obvious fix

**Comment by khanghugo** [comment]
It is already fixed master branch. If you don't plan to submit any run then feel free to pull newer verion from Actions page. Otherwise, just don't use it for the time being. Or you can have bxt-rs on top of BXT as bxt-rs master branch version has the same exact cvar but with fix applied.

**Comment by SmileyAG** [comment]
This has already been fixed in https://github.com/YaLTeR/BunnymodXT/commit/78fd348ed738f47da9231a1308143e0066283bd7 in latest unreleased version, but the next release of BXT version will probably not come out in a soon time soon.

Closing that issue as fixed.
