### ISSUE TITLE
Custom triggers

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/BunnymodXT#5]
Add custom triggers, same style as Bunnymod Pro's cl_autocmd.

Another type of those could be custom triggers for LiveSplit, which would force the program to split once entered. This would allow for custom splits that aren't Maps or Chapters.

Make them exportable to a file (with mapnames and coordinates inside) so it could be loaded the next time you launch the game.

**Comment by arianon** [comment]
+1

**Comment by Matherunner** [comment]
Wouldn't be too hard to implement. You should be able to define arbitrary rectangles as custom triggers, and these planes will have finite sizes and not be infinite.

**Comment by YaLTeR** [comment]
Custom triggers in form of axis-aligned cuboids are done in the custom-triggers branch.

**Comment by YaLTeR** [comment]
And now it's in the latest BXT release.
