### ISSUE TITLE
[Enhancement] `R_DrawSequentialPoly` pattern for Opposing Force

### ISSUE THREAD

**Issue by quantumdude836** [YaLTeR/BunnymodXT#50]
Similar to "HL-4554" pattern (and same length), but the prologue is slightly different. This enables `bxt_wallhack` in OpForce.

`A1 ?? ?? ?? ?? 53 55 BD 01 00 00 00 8B 88 F8 02 00 00 56 3B CD 57 75 62 E8 ?? ?? ?? ?? 68 03 03 00 00 68 02 03 00 00`

**Comment by YaLTeR** [comment]
Thanks, could you submit a pull request?
