### ISSUE TITLE
Latest Steam HL update broke some patterns

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/BunnymodXT#52]
`Cbuf_Execute`, `Cmd_ExecuteString`, ` Cbuf_InsertText`, `Cbuf_AddText`, `Host_Reload_f`.

**Comment by raider34790** [comment]
Yea I hope this gets hotfixed soon, I was in the middle of a TAS & Segmented project.

**Comment by YaLTeR** [comment]
Just grab the GoldSource package and use the Steam build from there.

**Comment by YaLTeR** [comment]
Fixed by #55
