### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by kujod** [YaLTeR/BunnymodXT#522]
the debug shows alot of stuff like couldnt find __ and idk how to fix it i got hl from the 25th anniversary

**Comment by khanghugo** [comment]
BunnymodXT does not support HL25. At least not yet. Consider rolling back to legacy.

**Comment by kujod** [comment]
oh okok how do i choose legacy if i never bought hl before and also do u have a discord/discord server i can ask questions on

**Comment by khanghugo** [comment]
SourceRuns discord https://discord.com/invite/sourceruns

**Comment by SmileyAG** [comment]
Duplicate of https://github.com/YaLTeR/BunnymodXT/issues/466
