### ISSUE TITLE
cant find bunnymodxt.dll

### ISSUE THREAD

**Issue by drhbomb** [YaLTeR/BunnymodXT#524]
i cant get the 7z to work [it wont extract] so i downloaded the source code but i cant find the bunnymodXT.dll file so it wont work. please help. my copy of half life is on steam and i use  windows 10

**Comment by Nomad7** [comment]
You need a tool like 7zip (available from https://www.7-zip.org/ ) to extract .7z files.
The source code can be used to create your own .dll file but I don't think that's what you're trying to do :)

**Comment by drhbomb** [comment]
i tried using 7zip but i kept getting an error and for some reason when i download a 7z it downloads as a notepad document

**Comment by drhbomb** [comment]
nevermind it worked now! i think it was the version of 7zip that i had installled. thank you so much!

**Comment by drhbomb** [comment]
whoops i forgot to close
