### ISSUE TITLE
LibSDL2-2.0.so.0 crash

### ISSUE THREAD

**Issue by Joe0132134** [YaLTeR/BunnymodXT#529]
![image](https://github.com/YaLTeR/BunnymodXT/assets/136608188/8bff1cc1-d1b1-4bc5-85f3-df7f818592a1)
I'm using Injector.exe
`Injector.exe "C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hl.exe" -game valve`
latest release of half-life on steam

**Comment by khanghugo** [comment]
Does it work? Usually you don't need to worry about the logs. 

Just in case, what is the game version you are running on? Type `version` in the console. If it is above 8684 then BXT would not work

**Comment by Joe0132134** [comment]
understood, thanks.
