### ISSUE TITLE
BunnymodXT fails to compile for windows

### ISSUE THREAD

**Issue by thomasdziedzic** [YaLTeR/BunnymodXT#546]
I just cloned the repo (commit I'm using is https://github.com/YaLTeR/BunnymodXT/commit/56bb64c35190f79177b739b9b4abfc594a6122cb) and tried to build it on windows. I got the following error:

```
BunnymodXT\BunnymodXT\helper_functions.hpp(27,4): error C3861: 'EngineMsg': identifier not found
```

I then looked through the commit/ci history on github and saw that ci has been failing for windows builds for the exact same reason:
https://github.com/YaLTeR/BunnymodXT/actions/runs/10122561202/job/27994847466#step:7:127

This error started happening with this commit:
https://github.com/YaLTeR/BunnymodXT/commit/0e208181e3359939b580a9aaf951594245bc42fb

**Comment by YaLTeR** [comment]
Yeah, I merged a PR that's missing an include by accident. I'm waiting for @SmileyAG to fix it.

**Comment by thomasdziedzic** [comment]
As a workaround, I checked out the commit right before the failing commit which is 2c06fdaca2c7ecad27f27041e48003c89ac4952b.

I can confirm that this fixes the build, though I think this issue should stay open until master is fixed.

**Comment by SmileyAG** [comment]
My apologies. There was just a queue of requests and more is awaiting, and in one of them I forgot to add `#include` for `sptlib-wrapper.h` by accident, and that's why the build broke. I wrote in the discord a couple of days ago that I would fix it as soon as I sit down to make new queue of requests again in a few days, but it seems that this moment has come now.

**Comment by SmileyAG** [comment]
@thomasdziedzic Also, if you want to contact us directly and maybe ask some questions about the reverse-engineering and etc, you can join the SourceRuns Discord and find the channel `#goldsrc-tas`, that's where we communicate
Discord invite URL: https://discord.gg/sourceruns

**Comment by thomasdziedzic** [comment]
@SmileyAG thanks for fixing the issue!

Also thanks for the invite, I joined the discord channel.
