### ISSUE TITLE
No "bxt_tas_new" command

### ISSUE THREAD

**Issue by YourLocalAssistantGuy** [YaLTeR/BunnymodXT#559]
I was trying to play back half life once again to TAS and stuff, but when I tried the command, it didn't show or do anything, it just like do nothing when I enter the command even without the parameters, so help me if you can please and I'm thank you about it.

**Comment by YaLTeR** [comment]
It was renamed to bxt_tas_editor_new. Please also consider using [bxt-rs](https://github.com/YaLTeR/bxt-rs) and its TAS studio, which is a rewritten and massively improved TAS editor: https://youtu.be/zi3pw9iS1sk
