### ISSUE TITLE
Missing commands when using BXT in Half-Life mods

### ISSUE THREAD

**Issue by YoshiThePyro** [YaLTeR/BunnymodXT#58]
I've been encountering this issue for a while now but it hasn't bothered me enough to report it until recently. I don't require much of BXT, nor do I really understand how the mod really works. This is an issue with a number of singleplayer mods, but in particular I wish to experiment with speedrunning the mod Halfquake: Amen. Specifically the 2018 updated steam re-release contained within "[Halfquake Trilogy](https://store.steampowered.com/app/644320/Halfquake_Trilogy/)". My two main issues are that for reasons I do not yet know or understand, bxt_autohop and bxt_bhopcap and their related commands are not available. There are almost definitely other commands that fail to appear also. Here's a screencap I took of the BXT debug console:
![BXT pls](https://user-images.githubusercontent.com/52011751/59795055-4599b700-92d2-11e9-935d-83e9da56eed2.PNG)
Any help in resolving this issue would be greatly appreciated, and apologies in advance if the solution is already lying around somewhere and I missed it.

**Comment by YaLTeR** [comment]
Mods with custom client and server DLLs frequently have unique byte patterns for the required functions and so if you want support for a particular mod you need to find every missing byte pattern and add it to BXT. The process requires knowledge of C++, Assembly and reverse-engineering, if you aren't familiar with it your best bet is finding someone willing to do it for you.

**Comment by YoshiThePyro** [comment]
So it's not a simple fix, and you're correct that I'm not familiar with any of that.
### God damn it.
Thanks for the pointer though YaLTeR. Time to start searching. I suppose that's this issue closed.
