### ISSUE TITLE
LoadLibrary failed even though Bunnymod folder and Injector are in same folder

### ISSUE THREAD

**Issue by Alias23** [YaLTeR/BunnymodXT#6]
Tried running as admin as well, did not work. Help?

**Comment by YaLTeR** [comment]
Make sure you have the redistributables installed, if that doesn't help try this (rename to BunnymodXT.dll): https://yadi.sk/d/cYbfaVo5rdJdb

**Comment by YaLTeR** [comment]
@Alias23 hi did it work

**Comment by Alias23** [comment]
Hi, after the newest version of bunnymod xt it seems to be working fine now. Thanks!
