### ISSUE TITLE
Bunnyhop bug

### ISSUE THREAD

**Issue by Shaydowik** [YaLTeR/BunnymodXT#60]
Hello tryed out bunnyhop XT on many clients, but still have some issues with commands. 
On some HL Won clients (including goldsource) the bxt_autojump command is working, but not working bxt_hud commands. 
On some clients nothing is working.
Main thing is that the autojump is not working at all. 
System: windows 10.
Do you have some way to repair this bug?
![Безымянный2](https://user-images.githubusercontent.com/56358210/66496310-67a68780-eac3-11e9-940f-b3f8320bf567.jpg)
![Безымянный3](https://user-images.githubusercontent.com/56358210/66496311-683f1e00-eac3-11e9-9f0f-c9a622ffe150.jpg)
![Безымянный4](https://user-images.githubusercontent.com/56358210/66496312-683f1e00-eac3-11e9-9005-e38238fc4b20.jpg)
![Безымянный](https://user-images.githubusercontent.com/56358210/66496313-683f1e00-eac3-11e9-9181-ad22c8db8d0f.jpg)

**Comment by YaLTeR** [comment]
Please use the GoldSrc Package 1 or 2, you can find the download links here: https://forums.sourceruns.org/t/goldsrc-package-2-3/2634

Other clients may require adding memory patterns into BXT manually. This is not a quick task and requires having the client downloaded. I'm not sure anyone is willing to do that for non-popular clients.
