### ISSUE TITLE
Half-Life Opposing Force 1.1.2.2 crashes.

### ISSUE THREAD

**Issue by Ogar-the-best** [YaLTeR/BunnymodXT#61]
When I inject BXT in HL:OF and press New Game or Load Game it crashes. I use software mode because OpenGL lags **REALLY** hard. Why?
![Screenshot_3](https://user-images.githubusercontent.com/29043391/67157512-b0253700-f346-11e9-8d74-a0eb63f19908.png)
![Screenshot_4](https://user-images.githubusercontent.com/29043391/67157595-b5cf4c80-f347-11e9-9560-5a2ee086a615.png)
Label: Bug (forgot to insert it)

**Comment by YaLTeR** [comment]
It's probably latest Steam which someone needs to add support for after the recent update.

**Comment by Ogar-the-best** [comment]
Okay thanks! I found out that it works in OpenGL. Also, now I'm on my main pc. I had a problem on a laptop.

**Comment by YaLTeR** [comment]
Latest Steam support was added in 41123400c46b51efc3cf4e88edf0a142cf2f86cb.

**Comment by Ogar-the-best** [comment]
And now when injecting it just wont do anything like #79

**Comment by YaLTeR** [comment]
Injecting where? What game, what build? Send a debug console screenshot?
