### ISSUE TITLE
LoadLibrary failed, .dll then deletes itself

### ISSUE THREAD

**Issue by Novorossicus** [YaLTeR/BunnymodXT#69]
![bunnymodxt_bug](https://user-images.githubusercontent.com/59451429/71686245-95206b80-2d68-11ea-82a6-7e0289dcf6b4.png)

Whenever I run the .exe injector, it tells me "Successfully opened the process." However, the injector then returns the following message:
"LoadLibrary failed. This usually means that you don't have BunnymodXT.dll in the same folder as the injector." 
After that message is returned, a few seconds later the BunnymodXT.dll deletes itself from the folder.
(I guess this is more an issue with the injector than the .dll)

Running the injector as administrator returns the following message:
"Error opening process: access is denied."
The .dll does not delete itself this time.

What I have done, saw, and checked already; all of these don't fix the problem:
-message is shown even if hl.exe is not running
-checked if the redistributables are installed (both x86 and x64 are installed)
-reinstalled redistributables
-tried with .bat file (i.e. GoldSrc Package's .bat files)
-tried to use a shortcut to the injector
-running as administrator

Version tested on: 1.1.2.2 (doesn't work)

#6 link is dead

**Comment by YaLTeR** [comment]
That sounds like it's your antivirus deleting the DLL. Add bxt to exceptions.

**Comment by YaLTeR** [comment]
Was the issue solved?

**Comment by Novorossicus** [comment]
Sorry for the late response. I excluded the files from being checked and it worked. Damn it, the problem was so simple. Anyways, thanks!

**Comment by anthonyop2024-cmd** [comment]
I have this problem but its not work
