### ISSUE TITLE
Allow client-side camera to be independent from the server

### ISSUE THREAD

**Issue by Matherunner** [YaLTeR/BunnymodXT#7]
Add a command/cvar that toggles independence between client and server cameras, so that we'll be able to arbitrarily move the camera around without affecting the server physics. Primary use cases based on my experience:

- visually monitor parts of a map before the character actually arrives there
- view what's happening behind your back while you're moving forward

This can be done by e.g. modifying the `pparam` argument passed to `V_CalcRefdef`.

**Comment by YaLTeR** [comment]
How would the camera movement part go? Just simple bxt_cam_{x,y,z,pitch,yaw,roll} or something more sophisticated like toggling a "freecam" state where you can move freely in a noclip-like fashion?

**Comment by Matherunner** [comment]
I'm thinking mostly of simple commands specifying a fixed camera position. So you could e.g. instantly teleport to examine how some door somewhere reacted to a button you've just toggled. Freecam might not actually be that useful in practice, plus it's trickier to implement.

**Comment by Matherunner** [comment]
Added in 2c4bee1fb692571b0dfc4710cf141c475ee09bd2 and b2c9d328de985ee343b13eacf299e7f6f558c719.
