### ISSUE TITLE
Running BXT on half-life or half-life mods on steam

### ISSUE THREAD

**Issue by fadespeedrunshl1** [YaLTeR/BunnymodXT#77]
When I use the BXT Injector when trying to run it on the Half-Life steam version or on half life mods such as TWHL mod it sits there for a second and then says "LoadLibrary failed. This usually means that you don't have BunnymodXT.dll in the same folder as the injector." even though I do have the bunnymodxt.dll in the same folder as the injector. Does anyone know a fix to this?

**Comment by YaLTeR** [comment]
Try disabling your antivirus.

**Comment by fadespeedrunshl1** [comment]
I had to disable Real-Time scanning on my mcafee antivirus program and it worked. Thanks :)
