### ISSUE TITLE
Bunnymod XT Lag

### ISSUE THREAD

**Issue by fadespeedrunshl1** [YaLTeR/BunnymodXT#78]
![2020-01-11](https://user-images.githubusercontent.com/59753405/72213900-ab869f80-34ab-11ea-81bc-971e8bef83b0.png)

When I try to play half life or any expansion packs for it the game starts to lag after a couple minutes after injecting bxt and i get this message in the debug console. Im not sure if the screenshot above will give you any information on to why this is happening but i thought id post it anyway.

**Comment by YaLTeR** [comment]
Does it happen without bxt?

**Comment by fadespeedrunshl1** [comment]
I tested it and it seems to only lag when bxt is injected and gets worse for some reason when I use the ingame bxt timer. I guess I don't have to have use bxt but in order to submit runs I kinda have to.

**Comment by YaLTeR** [comment]
Which package or otherwise build of the game are you using?

**Comment by fadespeedrunshl1** [comment]
GoldSrc Package 1.36 but it does the same thing with the newer package and the half life steam versions and mods. Maybe its my end but I never had a problem with it until now.

**Comment by YaLTeR** [comment]
Until now? So it suddenly started happening without you doing anything?

**Comment by fadespeedrunshl1** [comment]
I took a break from speedrunning for a couple months to play other games and when I got back into it just a couple days ago it started happening. I've just not been launching bxt when speedrunning so it fixes the problem but i wanted to see if you knew anything about it or if i should just not use bxt.

**Comment by YaLTeR** [comment]
Could you try disabling the antivirus to see if this helps?

**Comment by fadespeedrunshl1** [comment]
For some reason I had this random antivirus program that I don't remember installing so i just unistalled it and all the lag and small problems I had when playing are now fixed. Now i can finally start getting back into speedruning the half-life games. Thanks
