### ISSUE TITLE
Game wont show bxt_autojump, only bxt_bhopcap and other stuff. 

### ISSUE THREAD

**Issue by Ogar-the-best** [YaLTeR/BunnymodXT#79]
I am using the newest version of steam HL, build 8308. And, if you need more info about the game, I tried it with Crack-Life:Campaign. In Half-Life:Trinity Renderers, theres only bxt_hud.

**Comment by YaLTeR** [comment]
bxt_autojump and bhopcap require patterns to be found pretty much for each mod. They will work in the base game and in supported mods.
