### ISSUE TITLE
How to create a crouch jump script?

### ISSUE THREAD

**Issue by 07416** [YaLTeR/BunnymodXT#95]
Sorry if this is self-evident, but "crouch" isn't mentioned in the wiki. I want to automate crouch-jumping
and bind to a key.

**Comment by 07416** [comment]
Sorry, does the following command essentially enable what I'm asking? I only tested briefly (now away from computer) and assumed that the jump height wasn't increased since I didn't notice "crouching" being performed.

`bind space "+bxt_tas_autojump"`

Feel free to close the issue if you can confirm.

**Comment by YaLTeR** [comment]
I'm not sure what you mean by "crouch jumping". Could you clarify?

**Comment by 07416** [comment]
> 
> 
> I'm not sure what you mean by "crouch jumping". Could you clarify?

Crouch while holding jump, essentially eliminating the need to press the crouch key. 

I've understood that creating a simple alias reduces your jump distance (not height), I asked the question if BunnymodXT has some better alternative implementation.

**Comment by YaLTeR** [comment]
Crouch before collision or before ground or before ceiling? All of these are available in TAS scripts, but not as regular commands.

**Comment by 07416** [comment]
> 
> 
> Crouch before collision or before ground or before ceiling? All of these are available in TAS scripts, but not as regular commands.

Before ceiling, if that refers to the max height of the jump.

thank you for the replies.

**Comment by YaLTeR** [comment]
I really don't quite understand what you want. You don't ever want to crouch simply "at the highest point of the jump". It's not beneficial in and of itself.

**Comment by 07416** [comment]
> 
> 
> I really don't quite understand what you want. You don't ever want to crouch simply "at the highest point of the jump". It's not beneficial in and of itself.

Thank you for clarifying.

Sorry for being unclear.

Something similar to this script (reduces jump distance to my knowledge, as I said):

```
bind space +duckjump
alias +duckjump "+jump;+duck"
alias -duckjump "-jump;-duck"
```

**Comment by YaLTeR** [comment]
Doing this doesn't change the jump distance (it only activates the LJ module if you have one if I'm not mistaken).
